import Head from 'next/head'
import Link from 'next/link'
import Create from '../../components/Create'
import styles from '../../styles/CreatePage.module.css'

const text2imgUrl = process.env.NEXT_PUBLIC_TEXT2IMG_URL;

export default function CREATE() {
    return (
      <>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
        </Head>
        <div className={styles.content}>
          <p className={styles.title}>プロンプト作成ページ</p>
          <Create url={text2imgUrl}/>
          <Link href="/crud/read">
            <div className={styles.button}>一覧ページへ</div>
          </Link>
        </div>
      </>
    )
  }
